### ISSUE TITLE
MsgPack

### ISSUE THREAD

**Issue by sebllll** [velcrome/vvvv-Message#1]
https://github.com/scopely/msgpack-sharp

that could be added as alternative for OSC?

**Comment by velcrome** [comment]
@sebllll 
i finally found the nerve to address serialisation again, and msgpack is now available for vvvv-Message.

its binary format is the briefest of all serialisations implemented yet, serialisation to Stream is crazy fast. deserialisation is quite expensive still (but a little less than OSC), but maybe utilizing the new MemoryComStream will help in the near future.

The cool thing is, msgpack (like json) fully supports nested messages and all supported Types (including raw, vectors, transform and color). Only Time is still a little bugged right now.
