### ISSUE TITLE
AsRaw (Message.Raw) doesn't serialize nested messages

### ISSUE THREAD

**Issue by microdee** [velcrome/vvvv-Message#12]
The proprietary serializer simply ignores data from nested messages (in other words it isn't recursive). Is there any practical reason for that?

**Comment by velcrome** [comment]
no, except practical effort not spent here.
it is unlikely that i will add it now, since i consider the proprietary serializer as obselete with the more widespread, much more compact and equally performant messagepack implementation

**Comment by microdee** [comment]
Oh that's a pretty nice stuff! If it stores numbers as binary and not human readable I'm absolutely into it!

**Comment by velcrome** [comment]
that it is, unless you know the schema and are really really into hex.
