### ISSUE TITLE
AsMessage (string) and null

### ISSUE THREAD

**Issue by fjenett** [velcrome/vvvv-Message#2]
I have trouble parsing JSON strings containing ```null``` with AsMessage (string).

```
{
  "a_value":null
}
```

**Comment by velcrome** [comment]
What would be the expected behaviour? 

I think skipping it would be the most reasonable answer, since we cannot even deduce a meaningful type from that property.

**Comment by velcrome** [comment]
fixed in master.

**Comment by velcrome** [comment]
replacement dll (for /core and /plugins directories) can be found [https://www.nuget.org/packages/VVVV.Packs.Message/](here)
