### ISSUE TITLE
Read (Message) avoid nill should have adjustable default value

### ISSUE THREAD

**Issue by sunep** [velcrome/vvvv-Message#4]

**Comment by velcrome** [comment]
I am tempted to take it out completely, would make Read a little simpler. In case a field of the message is not available or NIL, it will report so on the binsize output, which can be used with a zip (bin) to set any default you'd want.

use the output and the binsize output on the first two pins of the zip, and your default and a (binsize output != 0) on the other two

**Comment by velcrome** [comment]
hey @sunep 

good news:
![image](https://cloud.githubusercontent.com/assets/280537/20505665/c90f7192-b04e-11e6-9a09-eded34b557fd.png)

I made a very basic node, and a more complicated one with your feature request, and some more gimmicks.
